name: Terraform Dispatcher
on:
  workflow_dispatch:
    inputs:
      verb:
        description: 'Terraform Verb (plan, apply, or destroy)'
        required: true
        default: ''
        options:
          - plan
          - apply
          - destroy

env:
  AZURE_STORAGE_ACCOUNT_NAME: devops2sources
  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  DEVOPS_AZURE_PUBLIC_SSH: ${{ secrets.DEVOPS_AZURE_PUBLIC_SSH }}
  DEVOPS_AZURE_ADMIN_USER: ${{ secrets.DEVOPS_AZURE_ADMIN_USER }}
  AZURE_FILE_SHARE_NAME: devops-platforms
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TFSTATE_FILE_PATH: azure-vm/main/vm/build/terraform.tfstate
  TFVARS_FILE_PATH: azure-vm/main/vm/cc.auto.tfvars

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Provider Login
      run: bash provider_login.sh

    - name: Terraform files download
      run: |
        # az storage directory create --account-name $AZURE_STORAGE_ACCOUNT_NAME --account-key $AZURE_STORAGE_ACCOUNT_KEY --share-name $AZURE_FILE_SHARE_NAME --name terraform --fail-on-exist
        az storage file download --account-name $AZURE_STORAGE_ACCOUNT_NAME --account-key $AZURE_STORAGE_ACCOUNT_KEY --share-name $AZURE_FILE_SHARE_NAME --path $TFSTATE_FILE_PATH
        az storage file download --account-name $AZURE_STORAGE_ACCOUNT_NAME --account-key $AZURE_STORAGE_ACCOUNT_KEY --share-name $AZURE_FILE_SHARE_NAME --path $TFVARS_FILE_PATH
    
    - name: Terraform Run
      env:
        VERB: ${{ github.event.inputs.verb }}
      run: |
        terraform init
        if [[ $VERB == "plan" ]]; then
          terraform ${VERB}
        else
          terraform ${VERB} -auto-approve
        fi
        echo "Uploading TF State File..."
        az storage file upload --account-name $AZURE_STORAGE_ACCOUNT_NAME --account-key $AZURE_STORAGE_ACCOUNT_KEY --share-name $AZURE_FILE_SHARE_NAME --path $TFSTATE_FILE_PATH --source terraform.tfstate
    